const types = {
  NAME_APP: 'Libreria El Poeta',
  START: 'Inicio',
  TASK_LIST_TITLE: 'Lista de Libros',
  SERVER_ERROR_MESSAGE: 'Hubo un problema con el servidor. Por favor, inténtalo más tarde o contacta a los desarrolladores.',
  EDIT_MODAL_TITLE: 'Editar Libro',
  ADD_TASK: 'Agregar Libro',
  ADD_NEW_TASK: 'Agregar un nuevo Libro',
  ADD: 'Agregar',
  CONFIRMATION_MESSAGE: '¿Estás seguro de que deseas guardar los cambios?',
  CONFIRMATION_ADD_TASK: '¿Estás seguro de que deseas agregar esta tarea?',
  DELETE_CONFIRMATION_MODAL_MESSAGE: '¿Estás seguro de que deseas eliminar esta tarea?',
  SAVE_BUTTON: 'Guardar Cambios',
  TITLE_LABEL: 'Título',
  DESCRIPTION_LABEL: 'Descripción de libro',
  STATUS_COMPLETE: 'Inventario completo',
  STATUS_NO_COMPLETE: 'Inventario pendiente',
  CANCEL_BUTTON: 'Cancelar',
  CONFIRM_BUTTON: 'Confirmar',
  PREVIOUS_PAGE_BUTTON: 'Anterior',
  NEXT_PAGE_BUTTON: 'Siguiente',
  ID_INCREMENTAL: 'ID',
  STATUS_LABEL: 'Estado de libro ',
  STOCK_LABEL: 'Stock',
  ACTIONS_LABEL: 'Acciones',
  EDIT_TASK: 'Editar',
  DELETE: 'Eliminar',
  PREVIOUS_NAVIGATION: 'Anterior',
  AFTER_NAVIGATION: 'Siguiente',
  CONFIRM: 'Confirmación',
  CONFIRM_DELETION: 'Confirmación de Eliminación',
  COMPLETE: 'Completado',
  SAVE: 'Guardar',
  PLEASE_ENTER_TITLE: 'Por favor, ingresa un título.',
  PLEASE_ENTER_DESCRIPTION: 'Por favor, ingresa una descripción.',
  INVENTARIO_DE_LIBROS: 'Inventario de Libros',
  GENERATE_PDF: 'Generar Informe',
};

export default types;
